api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
#    use_symfony_listeners: true
#    enable_docs: false
#    enable_entrypoint: false
#    enable_swagger: false
#    enable_swagger_ui: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header